name: EngAce Frontend

on: [push]

env:
  AZURE_WEBAPP_NAME: engace-app   
  AZURE_WEBAPP_PACKAGE_PATH: 'engace.web'
  NODE_VERSION: '20.x'               

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@master
   
    - name: Setup Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: 'npm install, build, and test'
      run: |
        cd engace.web
        npm install
        npm run build --if-present
        npm run test --if-present
      working-directory:  .
               
    - uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
